[build]
  command = ""
  functions = "netlify/functions"
  publish = "public"

[functions]
  included_files = ["views/**", "seo/**"]
  node_bundler = "esbuild"
  external_node_modules = ["ejs", "express-ejs-layouts"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
